### ISSUE TITLE
代码运行bug

### ISSUE THREAD

**Issue by linfenxuan** [JiaangL/REPORT#1]
Q1：
  File "/data2/fenxuan/REPORT/model/graph_encoder.py", line 118, in forward
    q, k, v = self.__compute_qkv(queries, keys, values, self.n_head, self.d_key, self.d_value)
TypeError: __compute_qkv() takes 4 positional arguments but 7 were given

____compute_qkv() 函数所需参数过多。

Q2：
File "/data2/fenxuan/anaconda3/envs/report/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1177, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'HierarchyTransformer' object has no attribute 'get_bce_loss'

定义HierarchyTransformer对象的时候 没有定义get_bce_loss

Q3：
FileNotFoundError: [Errno 2] No such file or directory: 'ckpts/fb237_v1/64_0.001_128_4_best_yet'

代码需要写一个创建文件夹的代码。

**Comment by JiaangL** [comment]
Sorry about the mistakes. I've fixed these typos in the latest version. Please let me know if there are more questions.

**Comment by 66lxy** [comment]
你好，我在预处理时出现了这样的问题：
$ bash preprocess_data.sh
+ set -o pipefail
+ python preprocess_ind_data.py --task fb237_v1
number of links in train is:4245
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\ps38\lib\threading.py", line 932, in _bootstrap_inner
D:\liuxueyang\model\REPORT-main\data_raw\fb237_v1\train.txt Extracting Path...:   0%|                                                                                                                            | 0/4245 [00:00<?, ?it/s]
   self.run()
  File "C:\ProgramData\Anaconda3\envs\ps38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\envs\ps38\lib\multiprocessing\pool.py", line 519, in _handle_workers
    cls._wait_for_updates(current_sentinels, change_notifier)
  File "C:\ProgramData\Anaconda3\envs\ps38\lib\multiprocessing\pool.py", line 499, in _wait_for_updates
    wait(sentinels, timeout=timeout)
  File "C:\ProgramData\Anaconda3\envs\ps38\lib\multiprocessing\connection.py", line 879, in wait
    ready_handles = _exhaustive_wait(waithandle_to_obj.keys(), timeout)
  File "C:\ProgramData\Anaconda3\envs\ps38\lib\multiprocessing\connection.py", line 811, in _exhaustive_wait
    res = _winapi.WaitForMultipleObjects(L, False, timeout)
ValueError: need at most 63 handles, got a sequence of length 74
想请问一下这是因为什么呢

**Comment by JiaangL** [comment]
Hi @66lxy ,

Thanks for reaching out and providing the details. I've checked the Internet and found something relevant to your issue. The error you're encountering, `ValueError: need at most 63 handles, got a sequence of length 74`, is related to the limitations of `multiprocessing` on **Windows**, specifically the `WaitForMultipleObjects` function, which restricts the number of handles to 63.

In your case, you have 74 handles, exceeding this limit. You can try decreasing the number of threads used for parallel processing to ensure it stays below the Windows limit. Moreover, you may switch to other OSs like Ubuntu, where this repo was originally tested.

Please explore these suggestions, and let us know if any of them help resolve the issue, by commenting below. I'll close this issue by now. But feel free to open a new one if you have any follow-up questions. :)
